---
development:
  dialect: postgres
  database: buffalo_test_development
  user: buffalo
  password: 'Admin123!'
  host: 127.0.0.1
  pool: 5

test:
  dialect: postgres
  database: buffalo_test_test
  user: buffalo
  password: 'Admin123!'
  host: 127.0.0.1
  pool: 5

production:
  dialect: postgres
  database: buffalo_test_production
  user: buffalo
  password: 'Admin123!'
  host: 127.0.0.1
  pool: 5
